// Generated by Wrangler
// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`
interface CloudflareBindings {
    D1: D1Database
    GOOGLE_CLIENT_ID: string
    GOOGLE_CLIENT_SECRET: string
    API_URL: string
    JWT_SECRET: string
    BASE_URL: string
}
