// Generated by Wrangler
// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`
interface CloudflareBindings {
    DB: D1Database
    webauthn_kv: KVNamespace
    GOOGLE_CLIENT_ID: string
    GOOGLE_CLIENT_SECRET: string
    API_URL: string
    JWT_SECRET: string
    BASE_URL: string
    TEST_BASE_URL: string
    X_API_KEY: string
}
