name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4

      # 安裝 pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # 忽略 workspace 根目錄檢查
      - name: Set pnpm config
        run: pnpm config set ignore-workspace-root-check true

      # 安裝 wrangler
      - name: Install wrangler
        run: pnpm add wrangler@3.109.2

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
