name: Deploy Frontend (Turbo Monorepo)

on:
  push:
    branches: ['**']
    paths:
      - 'apps/frontend/**'
      - 'apps/xincheng-managerment/**'
      - 'apps/hygeia-health/**'
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'apps/frontend/**'
      - 'apps/xincheng-managerment/**'
      - 'apps/hygeia-health/**'

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      xincheng: ${{ steps.filter.outputs.xincheng }}
      hygeia: ${{ steps.filter.outputs.hygeia }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            frontend:
              - 'apps/frontend/**'
            xincheng:
              - 'apps/xincheng-managerment/**'
            hygeia:
              - 'apps/hygeia-health/**'

  build:
    name: Build Apps
    needs: changes
    if: ${{ needs.changes.outputs.frontend == 'true' || needs.changes.outputs.xincheng == 'true' || needs.changes.outputs.hygeia == 'true' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [
          { name: 'frontend', path: 'frontend', condition: 'needs.changes.outputs.frontend == "true"' },
          { name: 'xincheng', path: 'xincheng-managerment', condition: 'needs.changes.outputs.xincheng == "true"' },
          { name: 'hygeia', path: 'hygeia-health', condition: 'needs.changes.outputs.hygeia == "true"' }
        ]
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build ${{ matrix.app.name }}
        if: ${{ matrix.app.condition }}
        run: pnpm run build --filter=${{ matrix.app.path }}
        env:
          DISABLE_ESLINT_PLUGIN: true
          NEXT_TELEMETRY_DISABLED: 1
